// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDimGmqj6gnh3yw7S-wQ3DbMBZ02ejlP_o',
    appId: '1:147371491698:web:26af1641a0ced809bc5deb',
    messagingSenderId: '147371491698',
    projectId: 'oua-app-jam',
    authDomain: 'oua-app-jam.firebaseapp.com',
    storageBucket: 'oua-app-jam.appspot.com',
    measurementId: 'G-2V1CBBFF1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCALKW16n01wstv_uIm6c4eMj0xuWQRFX4',
    appId: '1:147371491698:android:15e8f6e298682cddbc5deb',
    messagingSenderId: '147371491698',
    projectId: 'oua-app-jam',
    storageBucket: 'oua-app-jam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ55DlMv2SfBODCnGM7fIBJf2OLUVz4R4',
    appId: '1:147371491698:ios:b6082fe17b17b273bc5deb',
    messagingSenderId: '147371491698',
    projectId: 'oua-app-jam',
    storageBucket: 'oua-app-jam.appspot.com',
    iosClientId: '147371491698-u1s6u8gn8tj84t7lvlnm2seidpsbea48.apps.googleusercontent.com',
    iosBundleId: 'com.example.appJamUygulama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ55DlMv2SfBODCnGM7fIBJf2OLUVz4R4',
    appId: '1:147371491698:ios:b6082fe17b17b273bc5deb',
    messagingSenderId: '147371491698',
    projectId: 'oua-app-jam',
    storageBucket: 'oua-app-jam.appspot.com',
    iosClientId: '147371491698-u1s6u8gn8tj84t7lvlnm2seidpsbea48.apps.googleusercontent.com',
    iosBundleId: 'com.example.appJamUygulama',
  );
}
